export default {
  docs: [
    {
      type: "category",
      label: "Projects",
      link: { type: "doc", id: "projects/auth-system/01-overview" },
      items: [{ type: "autogenerated", dirName: "projects" }],
    },
    {
      type: "category",
      label: "Architecture",
      link: { type: "doc", id: "architecture/e-commerce/01-home-page" },
      items: [{ type: "autogenerated", dirName: "architecture" }],
    },
    {
      type: "category",
      label: "Notes",
      link: { type: "doc", id: "notes/docker-tips" },
      items: [{ type: "autogenerated", dirName: "notes" }],
    },
  ],
};
